default_title: StartupDecode by Amine Sadry
meta_keywords: "ruby on rails, ruby, tutorials,startup, do it yourself"
meta_description: "StartupDecode: The easiest way to learn coding for inspiring entrepreneurs!"